main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

trailer:
  method: 'get'
  path: trailer/{trailer_id}
  controller: App\Controller\HomeController
  action: trailerCard
  requirements:
    page: '\d+'